### ISSUE TITLE
Regroupement sur KR P32

### ISSUE THREAD

**Issue by ClemGLAD** [devteamreims/devteamreims.github.io#1]
Salut,

Voici les propositions de 4ME sur un KR en P32 (bug CDS) : UB,UN,KR & HN,KR
J'ai essayé sans succès de joindre une copie d'écran.

++

**Comment by kouak** [comment]
Résolu ici : https://github.com/devteamreims/4me.core.mapping/commit/419fa9448e651e9b96a41b76a0a379a98b986839

Les reports de bugs doivent être déposés dans ce dépot : https://github.com/devteamreims/4ME/issues

Merci pour le report !
